import { NextPage } from 'next'
import Head from "next/head"
import LandingP from '@/components/landingpage'
import CardsContainer from '@/components/cardscontainer'
import Footer from '@/components/footer'
import { Poppins, Montserrat} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Center, Grid, GridItem} from '@chakra-ui/react'
import { Heading } from '@chakra-ui/react';
import { ChakraProvider } from '@chakra-ui/react'
import { title } from 'process'


// import Image from 'next/image'

// Grid:  https://chakra-ui.com/docs/components/grid/usage
const poppins = Poppins({
  subsets:['latin'],
  weight:['200','400']
})
const montserrat = Montserrat({
  subsets:['latin'],
  weight:['200','300','400']
})
const Home:NextPage = () => {

  const cards = [
    {
      id:'1',
      title:'My Biography',
      description: 'A little introduction about who I am',
      image:'/img/computer.jpg'
    },
    {
      id:"2",
      title:'Training and Short Course Experience',
      description: 'I love learn something new about IT. So look at my training experience',
      image:'/img/growtika-2.jpg'
    },
    {
      id:"3",
      title:'Projects',
      description: 'Always improve my skilss and you can view my training experience in here',
      image:'/img/growtika-3.jpg'
    },
    {
      id:"4",
      title:'Research',
      description: 'Some research when I was in college',
      image:'/img/growtika-1.jpg'
    }
  ];
  const containerStyle = {
    backgroundColor: '#333333',
    color: 'white', // Set text color to be visible on dark background
  };
  return (
    <>
    <Head>
      <title>Indah Mutiah MZ Website</title>
      <meta name="description" content="Generated by create-t3-app" />
    </Head>
    <main style={containerStyle} className={montserrat.className}>
      <ChakraProvider>
        <LandingP></LandingP>
        <Center>
        <Heading as={'h1'} size={'xl'} marginTop={50} marginBottom={50} id='cards'> MY TOPICS</Heading>
        </Center>
        
        {/* <Grid templateColumns='repeat(3, 1fr)' gap={6} >
          {cards.map((p) => <GridItem key={p.id}>
            <Cards ></Cards>
          </GridItem>)}  
        </Grid> */}
        <CardsContainer cards={cards} />
        
        <Footer></Footer>
      </ChakraProvider>
      
    </main>
    </>
  );
};


export default Home;
