import { NextPage } from 'next'
import Head from "next/head"
import LandingP from '@/components/landingpage'
import Cards from '@/components/cards'
import Footer from '@/components/footer'
import styles from '@/styles/Home.module.css'
import {Grid, GridItem} from '@chakra-ui/react'
// import Image from 'next/image'

// Grid:  https://chakra-ui.com/docs/components/grid/usage
const Home:NextPage = () => {

  const products = [
    {
      id: 'cards1',
      name: 'Product',
    },
    {
      id: 'cards2',
      name: 'Product 2',
    },
    {
      id: 'cards3',
      name: 'Product 2',
    },
    {
      id: 'cards4',
      name: 'Product 2',
    },
    {
      id: 'cards5',
      name: 'Product 2',
    },
    {
      id: 'cards6',
      name: 'Product 2',
    }
  ]

  return (
    <>
    <Head>
      <title>Indah Mutiah MZ Website</title>
      <meta name="description" content="Generated by create-t3-app" />
    </Head>
    <main>
      <LandingP></LandingP>

      <br></br>
      
      <Grid templateColumns='repeat(3, 1fr)' gap={6} >
        {products.map((p) => <GridItem key={p.id}>
          <Cards ></Cards>
        </GridItem>)}  
      </Grid>
      
      <Footer></Footer>
    </main>
    </>
  );
};


export default Home;
